---
clusterName: ${CLUSTER_NAME}

# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.6.0
# renovate: datasource=github-releases extractVersion=^v(?<version>.*)$ depName=kubernetes/kubernetes
kubernetesVersion: 1.28.3

endpoint: "https://${CLUSTER_NAME}.${INTERNAL_DOMAIN}:6443"

allowSchedulingOnMasters: true
allowSchedulingOnControlPlane: true

clusterPodNets:
  - 172.22.0.0/16
clusterSvcNets:
  - 172.23.0.0/16

cniConfig:
  name: none

additionalApiServerCertSans:
  - ${CLUSTER_ENDPOINT_IP}
  - ${EXTERNAL_CLUSTER_NAME}.${EXTERNAL_DOMAIN}

additionalMachineCertSans:
  - ${CLUSTER_ENDPOINT_IP}
  - ${CLUSTER_NAME}.${INTERNAL_DOMAIN}
  - ${EXTERNAL_CLUSTER_NAME}.${EXTERNAL_DOMAIN}

nodes:
  # intel nuc panther canyon / i7 / 256GB / 1TB SSD / 2TB Nvme
  - hostname: tiny-001.${INTERNAL_DOMAIN}
    controlPlane: true
    ipAddress: 192.168.1.83
    installDisk: /dev/nvme1n1
    disableSearchDomain: true
    nameservers:
      - "192.168.1.131"
    networkInterfaces:
      - interface: enp2s0f0u2u3
        addresses:
          - "192.168.1.83/24"
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.254
            metric: 1024
        dhcp: false
        vip:
          ip: ${CLUSTER_ENDPOINT_IP}
    nodeLabels: &controlPlaneLabels
      plan.upgrade.cattle.io/talos: ""
      topology.kubernetes.io/region: pick
      topology.kubernetes.io/zone: pick-u
  # intel nuc panther canyon / i7 / 256GB / 1TB SSD / 2TB Nvme
  - hostname: tiny-002.${INTERNAL_DOMAIN}
    controlPlane: true
    ipAddress: 192.168.1.115
    installDisk: /dev/nvme1n1
    disableSearchDomain: true
    nameservers:
      - "192.168.1.131"
    networkInterfaces:
      - interface: enp1s0
        dhcp: false
        addresses:
          - "192.168.1.115/24"
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.254
            metric: 1024
        vip:
          ip: ${CLUSTER_ENDPOINT_IP}
    nodeLabels: *controlPlaneLabels


controlPlane:
  patches:
    - |-
      cluster:
        proxy:
          disabled: true
        etcd:
          advertisedSubnets:
            - 192.168.1.0/24
        extraManifests:
          - https://raw.githubusercontent.com/drduker/homelab/main/infrastructure/talos/integrations/cni/cilium.yaml
          - https://raw.githubusercontent.com/drduker/homelab/main/infrastructure/talos/integrations/kubelet-csr-approver/kubelet-csr-approver.yaml

    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - system

        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true

        # install:
        #   extensions:
        #     - siderolabs/amdgpu-firmware
        #     - siderolabs/util-linux-tools
        #     - image: ghcr.io/siderolabs/nvidia-open-gpu-kernel-modules:535.129.03-v1.6.0
        #     - image: ghcr.io/siderolabs/nvidia-container-toolkit:535.129.03-v1.13.5
        #     - image: ghcr.io/siderolabs/nvidia-fabricmanager:535.129.03
        kubelet:
          extraArgs:
            feature-gates: CronJobTimeZone=true,GracefulNodeShutdown=true,NewVolumeManagerReconstruction=false
            rotate-server-certificates: "true"
          extraConfig:
            maxPods: 250
          nodeIP:
            validSubnets:
              - 192.168.1.0/24

        network:
          extraHostEntries:
            - ip: ${CLUSTER_ENDPOINT_IP}
              aliases:
                - ${CLUSTER_NAME}.${INTERNAL_DOMAIN}

        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"

        time:
          disabled: false
          servers:
            - ${NTP_SERVER}
