CLUSTER_NAME: ENC[AES256_GCM,data:FAvZSk4UqWc=,iv:1TP/qD1rKbuBFf3DM8os3QMf+s175O1XM+XvdfEjikI=,tag:JYS+F4T1j3MDfzwzxkWaQw==,type:str]
EXTERNAL_CLUSTER_NAME: ENC[AES256_GCM,data:RZyA0ElRoXY=,iv:l+BebCeDlj4y5caDmD+RWKlYhu4mAQaERvk5lLVHoXk=,tag:xRBOc1x+iYmktQyWAoZMeA==,type:str]
CLUSTER_ENDPOINT_IP: ENC[AES256_GCM,data:YHib40dCSS7KIKB6ug==,iv:7WSef5hxEvjyEYe4m7+pC3TioPPiugsaWnM1H9QWWXg=,tag:CM6jxlN6sv7dgtwZXnuhcA==,type:str]
INTERNAL_DOMAIN: ENC[AES256_GCM,data:Quf04VlxgROkQ+i+F84Bg752,iv:d/YBQr+AOhNmmZugwMB8fXZopzg+SVCB+VMi437yMaM=,tag:BOyg2eX1YQWVq1SPfHLEww==,type:str]
EXTERNAL_DOMAIN: ENC[AES256_GCM,data:ER99IfCyPD0g,iv:kLn1fx3BIddwul5Dxjsi89r2Y0RDhd1o1qOU0pTwe/E=,tag:xVKpslTSDc2rDaNEXw1+Tg==,type:str]
DNS_SERVER: ENC[AES256_GCM,data:m/LyO6umCCLUXCgvAw==,iv:xZ5Yp/BlFAaI+CK1mdmVzczMHvefQng7PriyZx0ztSU=,tag:z/igJcW7SKr0LlZ+sdgheQ==,type:str]
NTP_SERVER: ENC[AES256_GCM,data:eVgHEVpoul01DxGO,iv:t8UoKO329MRQu8Ipe5iMwmAHgnSe3FO+tP/mnYOV57M=,tag:jzqq/r1/sQxan8VvQnz5YA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p8hda0uw768yg608j8spnwx0fwu5ze88kpchufmgw4v87u2c84dsjns37d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVFZCSElVVVNQV1ByRjls
            TVhTUWlscGtJamlLTEZoSDJ6QW5UY25DcEZJCmJidXFHcGV1aG4vaWJ3eFVGTGhs
            YWliakVlMm5XZ0pVQno0OUsvbHdhNHcKLS0tIGwwcllNRkRUdHNSWFNpR0NNcXo4
            bmFrUm40M0hsa1dPNnl5SlVnVkcxTTQKd/XL1MbM0UgELJsHYbBRy+2r8ZgDUJWm
            ECeylBF4MDiw+7UxubINGNXfXEmf2shY1YZJMTqsTya8T0Li3NKs6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T01:42:55Z"
    mac: ENC[AES256_GCM,data:k3sezxkC1TwrBPrl9s3nKlX4NHP98dyyRF/56eJ9YdTvBwRYAhU2LGUeIUmJw2KxnDAGEuQPIisBy9DWWJlCp3TtST8ADv6gE6wPYX+sURBuXQ9FEa7+7W67R1SstUBEwUKC8GfsA8ooijM2I9FHWuYLkQbJs8Iq9tpOGCcdkn4=,iv:0RO6R+JVkl9+bmZu4GFbbxj/MGFEH/lUnEx/OmG/Gkw=,tag:aqG/xqtuB+jA/qNXgcNFng==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
