CLUSTER_NAME: ENC[AES256_GCM,data:Ez/3Ey5R2mg=,iv:I5Clgvx+ytwbp5kkJFB4DF92TDOMykU72FTiVdmbG6k=,tag:1gxdh9AXhcCgofr0covU3w==,type:str]
EXTERNAL_CLUSTER_NAME: ENC[AES256_GCM,data:cMn085/rMUI=,iv:eaL1+ZvXUXG3UzD5qNHnBbWCOjLB38RkbFHVx9TKsVs=,tag:w5kGWI9h5oHeqzZkI0fWYg==,type:str]
CLUSTER_ENDPOINT_IP: ENC[AES256_GCM,data:/YlJk3m6KYCtxxb0Bg==,iv:onK4E9/TPln4csvJmO9CSagcUneLEaTprA4lwGtzOjU=,tag:yaUiWZ1pk94XVG/6KezNeA==,type:str]
INTERNAL_DOMAIN: ENC[AES256_GCM,data:eQVKbllOL5/KrHqOUGmPYF4S,iv:TzHBMu9PoNvYr9QygpT53LA9a+7TfWULvASHjYR0HCE=,tag:69GP/vGXyc6cUgwseNVwmw==,type:str]
EXTERNAL_DOMAIN: ENC[AES256_GCM,data:4o40Rxv74nQz,iv:eMcGtcTiJ32i/GNE05flFkH09rz5bBxCMI413pvHoe8=,tag:bwuAuf01yKbPmR/8+HczIw==,type:str]
DNS_SERVER: ENC[AES256_GCM,data:c/WyzXz4LLAU9k68Eg==,iv:OVIBtanuB3tDwOk53mOyRmfzbgCiATjQT2BzQ3cQy68=,tag:tM+bftPkQFHecVSI1mhLgA==,type:str]
NTP_SERVER: ENC[AES256_GCM,data:oRBh51hvNYIt/QwUq45AydMvag==,iv:augmIELXYNWZnDGIhfnMVrgxywFPUlqu5YLvbB1poMQ=,tag:UDLW+gLvNGCK8bw8oy3tLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p8hda0uw768yg608j8spnwx0fwu5ze88kpchufmgw4v87u2c84dsjns37d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRmRxTlBoT0RLYktwTDlm
            ZlRPd2NYUHlXNTJORExRck52WlJCUmp3VUI0CjVMTjBodnltWHZBSnlZZ0ROd1dO
            NlRzZzliZTQ0VEc5Z0FEK2w1RWR2L2sKLS0tIFZpZFpuaE8wOWNjSnhsQU11K0lp
            R1ZKblcwM0g5dHhCVHZSQkY1SnM2a3MKPGNtGeQT1Z6ohl4DRFzPN/SvetBLwrDv
            /BOodkzsAKkb8UmTZBw5B0lyY5B/m2dUprdxhVYFgIF/mG/07PdqKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T04:27:47Z"
    mac: ENC[AES256_GCM,data:jk/HFM6z71ZtDDj8myoQ7KyoLFelFWeM6TLlRJlGqQ26zKxaKq7J46kvO9qaopPNsm25x5Bc1VXCk6Ceoiai5w3I/GVmd7HN/HX8zXr6ysbVwU8+2ERvkb5VJp8nbj0g8PsBtrESBhxxfkMk2E9suL3FS6sN8/y5Ye6Y8bnlKcI=,iv:TJZ08pf+zRL4xCmAshIs8ji2K1o9UNJ1Q0ZxiPjqvqo=,tag:T8k2xkblRaZ/5AZh2+IjPw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
