---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: oci-drduker
  namespace: flux-system
spec:
  interval: 1m
  url:  oci://ghcr.io/drduker/charts
  ref:
    tag: main
