---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: oci-terraform-authentik
  namespace: flux-system
spec:
  interval: 1m
  url: oci://ghcr.io/drduker/terraform/authentik
  ref:
    tag: main
