---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: keycloak
      version: 2.5.1-bb.5
      sourceRef:
        kind: HelmRepository
        name: drduker
        namespace: flux-system
      interval: 30m
  values:
    replicas: 1
    args:
      - "start-dev"
    extraEnv: |-
      - name: KC_HTTPS_CLIENT_AUTH
        value: request
      - name: KC_HOSTNAME
        value: login.pick.haus
      - name: KC_LOG_LEVEL
        value: "org.keycloak.events:DEBUG,org.infinispan:INFO,org.jgroups:INFO"
      - name: QUARKUS_HTTP_ACCESS_LOG_ENABLED
        value: "true"
      - name: KC_HOSTNAME_STRICT
        value: "false"
      - name: KC_HOSTNAME_STRICT_HTTPS
        value: "false"
      - name: KC_PROXY_HEADERS
        value: xforwarded
      - name: KC_PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KC_HTTP_ENABLED
        value: "true"

    secrets:
      env:
        stringData:
          JAVA_OPTS_APPEND: -Djgroups.dns.query=keycloak-headless.keycloak.svc.cluster.local
      quarkusproperties:
        stringData:
          quarkus.properties: |-
            quarkus.http.non-application-root-path=/
            quarkus.kc-routing.path-redirect./=/auth/realms/haus/account
            quarkus.kc-routing.path-redirect./auth=/auth/realms/haus/account
            quarkus.kc-routing.path-redirect./register=/auth/realms/haus/protocol/openid-connect/registrations?client_id=account&response_type=code
            quarkus.kc-routing.path-prefix./oauth/authorize=/auth/realms/haus/protocol/openid-connect/auth
            quarkus.kc-routing.path-filter./api/v4/user=/auth/realms/haus/protocol/openid-connect/userinfo
            quarkus.kc-routing.path-filter./oauth/token=/auth/realms/haus/protocol/openid-connect/token
            quarkus.kc-routing.path-recursive-block./metrics=8443
            quarkus.kc-routing.path-recursive-block./health=8443
            quarkus.http.cors=true
            quarkus.http.cors.methods=OPTIONS,POST,GET,PATCH,PUT,DELETE
            quarkus.http.cors.headers=Content-Disposition,Access-Control-Allow-Headers,Content-Type,Authorization,X-Requested-With
            quarkus.http.cors.access-control-max-age=24H
            quarkus.http.cors.access-control-allow-credentials=true
            quarkus.http.cors.origins=*

    dbchecker:
      image:
        repository: r.gamewarden.io/base/postgres-cloudnative-pg
        tag: '16.4-r0'
    image:
      repository: quay.io/keycloak/keycloak
      tag: "26.0.8"
    postgresql:
      volume:
        storageClass: ceph-block
      image:
        registry: r.gamewarden.io
        repository: base/postgres-cloudnative-pg
        tag: '16.4-r0'
      securityContext:
        fsGroup: 70
        runAsUser: 70
        runAsGroup: 70
      containerSecurityContext:
        runAsUser: 70

# - auth.${EXTERNAL_DOMAIN}