apiVersion: v1
kind: Secret
metadata:
    name: internal-dns-secret
stringData:
    EXTERNAL_DNS_RFC2136_TSIG_KEYNAME: 
    EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG: 
    EXTERNAL_DNS_RFC2136_TSIG_SECRET: 