apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitor
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: flux-system
stringData:
    GF_AUTH_GENERIC_OAUTH_API_URL: changeme
    GF_AUTH_GENERIC_OAUTH_AUTH_URL: changeme
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: changeme
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: changeme
    GF_AUTH_GENERIC_OAUTH_TOKEN_URL: changeme
    GF_AUTH_SIGNOUT_REDIRECT_URL: changeme
