# Name of the tunnel you want to run
tunnel: test-tunnel
credentials-file: /etc/cloudflared/creds/credentials.json
# Serves the metrics server under /metrics and the readiness server under /ready
metrics: 0.0.0.0:2000
no-autoupdate: true
# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
ingress:
- hostname: 'ollama.pick.haus'
  service: https://ollama-ui.ai.svc.cluster.local:8080
- hostname: '*.pick.haus'
  service: http://cilium-gateway-public-gateway.network.svc.cluster.local:80
# - hostname: '*.homelab.ing'
#   service: https://cilium-gateway-public-gateway.network.svc.cluster.local:443
# This rule matches any traffic which didn't match a previous rule, and responds with HTTP 404.
- service: http_status:503
