---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-apps-cloudflared
  namespace: network
resources:
- deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: cloudflared
  files:
  - config.yaml

secretGenerator:
- name: tunnel-credentials
  namespace: network
  files:
  - credentials.json
- name: tunnel-origin-cert
  namespace: network
  files:
  - cert.pem
