apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    EMAIL_ADDRESS: ENC[AES256_GCM,data:mLhZMAlLk5ZGt2Ll/oKHr+Gy5w==,iv:J/YBYVLk4C7idaSHoumkNev3TRNhNNNlkhPkVToSndM=,tag:FyGh/1rFSM47RofTawzjvA==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:72WcApxXIuEX,iv:KHSjf7vnIf6FPW3zC3uWkSBP9+zxHZzvX9q4ksi7RPE=,tag:CZBc3pf31jPq/WsXkHa7Fw==,type:str]
    FULL_NAME: ENC[AES256_GCM,data:UqicNJVwlb8=,iv:R4TFTfGeawX0fdHz5ozwB8mY5xG9Uh6vdII+qvc4gQk=,tag:Y+zb3iOZbv+r+FnCoLWWYw==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:ql8bHl3aqwlRi8oJzvgHZmuP,iv:oWUI0tuvSBk5yMDrGgg1LxHbpsJOceUWoJPnWFWSpAc=,tag:bejlkyjZDDX7KDQPopFX1A==,type:str]
    PROFESSIONAL_DOMAIN: ENC[AES256_GCM,data:DWIbXa+zQTCzDCc=,iv:9KA4rqRm2UEUMr7TCRyk22yZQbHPYu2+WM30NRxoYXk=,tag:fwZ64qcURd4mDVSSPH+oOg==,type:str]
    SECRET_MAXMIND_ACCOUNT_ID: ENC[AES256_GCM,data:wrl2U1bEvCM=,iv:xnSRx20Fjznxl9IlYH/gdD4KRCVP3i5IYqPwDLaGRiA=,tag:1tzwhT9F7HnBsBEtmzKDRw==,type:str]
    SECRET_MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:7QGPU93pwdI=,iv:/MxJ802jv4+Up4qqK23he3s7FoTwyS7CfIy3vGYJ2VE=,tag:tUawowAvWkINRAOpyTIWpQ==,type:str]
    SECRET_SENDGRID_APIKEY_SMTP_RELAY: ENC[AES256_GCM,data:gPd5AI+GkCk=,iv:k8QX1+OJHrdxORo04QmmmanB0hJd/mxCFJPzprwh5mQ=,tag:cvFgirabqLOQlkMrqrL+5w==,type:str]
    SECRET_SENDGRID_USER_SMTP_RELAY: ENC[AES256_GCM,data:v7AdrhRKEic=,iv:JgaqKJHpH+LgHg0vmOgwtgIXBw5P53zmgwYcw7XqKlU=,tag:jVCkYYaFxW6OjTyJTiXyQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p8hda0uw768yg608j8spnwx0fwu5ze88kpchufmgw4v87u2c84dsjns37d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRFh0OUdWbUpXZGxKOFd4
            TU1EM0FyOHdVcEtxV1dna1FKSXA1eW9nT3dBCm5TTHNQbVE3WkVPdWJPRWJtRzVm
            OXBTQk9nWjFjVjh0Z0toNFV2eStrYzQKLS0tIG81ckxDWEswOFNGeStHWXdTSVhY
            U2FPZGsvRXpoUytEd0VsMEVpWG8yV28KIzOWvhLpuuem9xm2W60c0ELLi1xXEH1D
            L5nIKgg3ZuPkz/M6cwRSjxSn0hPCXAis8OT+aJ3Pp03GpW5rIJsOMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-16T21:54:42Z"
    mac: ENC[AES256_GCM,data:84YvklheBEuXqXn7Y9doVhuRbrVEzMCNFlIs1xLWlt4spn4T0hsKkDJmB+dLjfcQVvbudruvbsEEYR7UFqL0yyjC7ZzfmCuXVf57IBsyGaoNR5xWKB38twA12WrwzbYSOyljZcvJ58Ia9M+HrC4NIfQJJ4845JS66RX0HiA+y5k=,iv:WL8Rn5lG1nn1AzoYp812crH5TQWaHXcld/XQhpw5Y0M=,tag:Gf0oHwkk3fiydQKETuoQEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
