apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    EMAIL_ADDRESS: ENC[AES256_GCM,data:G2J/1Gu0UBIVuOzE0iRH6ytk6g==,iv:w9B6TcTmVV5jplNBrtzIrOD0siuzhebvip57xfh78pA=,tag:y8ICsEpsn3wCBML/GJ3ecw==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:sEhNqGP+Gpml,iv:xUmAmsre4L3mn/LP0N2QUpgaGrlgA06XBKuuXhoJq5Q=,tag:5s2F1qEKwchoL0KpkULaMA==,type:str]
    FULL_NAME: ENC[AES256_GCM,data:ymIaupBwQkQ=,iv:lcD78i63ZGPBCaqfqRoJKIjPkv7UobRf0B8e0jY6iLI=,tag:cwd2X5uhJI0O1R54VcjF4A==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:A8Ggblux0NhSbVWAQiUlyPmK,iv:PaqXAyGwWOtLVsBLGLfJd8MqJia+hu45rdghcw/MhdY=,tag:KU8nvoiycnsqO20zpkQWNw==,type:str]
    PROFESSIONAL_DOMAIN: ENC[AES256_GCM,data:gcHL//bbbRUeSsw=,iv:JFk9RP2rLjIwGuICFwqi9dU4mDrt7cGwVW8f3pg6ORg=,tag:2gjNAON4OeEwRxsKZZGH/Q==,type:str]
    SECRET_MAXMIND_ACCOUNT_ID: ENC[AES256_GCM,data:LhEm6wxaU1g=,iv:GunhmN8PuFRFIv6ZAVQDLxYZFTh+ZVU+laH5k+yvvpI=,tag:+kx9uPKJ6Eytm/VAnlANdw==,type:str]
    SECRET_MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:HYvQ4J2B1Ps=,iv:Okt6n5ygU4WvEHTy7+nvkTl/Oaw//1t+AEvNn1Ra0Iw=,tag:M4QKEfMW/Zx6wsQP8YedZQ==,type:str]
    SECRET_SENDGRID_APIKEY_SMTP_RELAY: ENC[AES256_GCM,data:ni8CNtJLZ1U=,iv:3+eGUqZ292rUyH2Q3TaoHCl7NzlsYC249B7jc3fT8Lc=,tag:DYVw7wOJAxvv7QvuxjPhug==,type:str]
    SECRET_SENDGRID_USER_SMTP_RELAY: ENC[AES256_GCM,data:K2yPqSAnUvY=,iv:AMZCMhyTt2nS3GBuSKJGn2rW9yZos6Oa4IVs8EzPsMA=,tag:1wpWq0RrsOyEdbk+hfpEVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p8hda0uw768yg608j8spnwx0fwu5ze88kpchufmgw4v87u2c84dsjns37d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdHVCOUZ1Z1dsUjQyUkly
            blIwN2pCS1NJVXEyMDRtUkxmZVo3ZEs5NUFrCnd0Vno4c0E2Z2dOQlI0YkVzOFdr
            TCtuKzU3Z1MrSmFZaWY4L2JyTzhXQmsKLS0tIGhpUXUzMlpjc2dabEdYZnl4SUlh
            YW52a1ZUQTAxNWZSMEJLdkRUVkNvVnMKahDpzYsvWkHoa6SUSdJMbG7/g8KVT5Bl
            N/wfMKpJNeDp7x8/3pu2B4noOvRAlmjErGwoH0eqUTC3qs4aUXyB4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-18T02:36:23Z"
    mac: ENC[AES256_GCM,data:BtT9jaQwhJ6W0Ku3sYbL03yRtBPBFWrqOmzNmLjtHON6M3210jqBaMXPv53JiyiAnFrP7cmsQEiWwHo+hXdivGPO7hPypmtc9U6alQeAEzO0R6Po8XUsYlsHjHAF0JuQBn4Mmt7yidH//GBxcEO+Xql5G5e7dFAL+ikCLmJ9Gho=,iv:R+bD48zKnREAZSTntmKbCKJj0Yvw1vf6tP4pCHIRE6w=,tag:HMjTeLN2eab1QkUCudiT3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
