apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    EMAIL_ADDRESS: ENC[AES256_GCM,data:AJSSdRXwem1hKAT2Sn3LBUsblQ==,iv:WE/1ZDMwoiHBNMXdG24AicFxgA40/fAZXii+kMzfXKA=,tag:yMFwZKoShQOLMFB1FcMHoA==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:Q6n5fxsyEBTX,iv:qmcrKt6i4gtj285kEZZw5/xsn5KsPfrO+rDCJQ3vHmQ=,tag:z4PSDljTiF6qGwT4mq8yoA==,type:str]
    FULL_NAME: ENC[AES256_GCM,data:PBK3CFgV77E=,iv:0Jp79msyXzZOTiMxGAiWvIWN0t8H23VDg+7bjHl/jrM=,tag:LY6+zk+sWKF2cgs19/Qg7A==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:Zvp3J52Pw7I=,iv:5z3gMMePUGIVKJKtncHtjDH50/FlbcJ7N7ZMxxDnXKU=,tag:YRzM4gPCYE/CdEzSw2p2dw==,type:str]
    PROFESSIONAL_DOMAIN: ENC[AES256_GCM,data:3CjdNTB6wII=,iv:5p9qto+NheiwJr0IguB1zCpfnh9M3XmvmDyHZfvx6c0=,tag:QiwyKnUIdWVb/kvJisNeZA==,type:str]
    SECRET_MAXMIND_ACCOUNT_ID: ENC[AES256_GCM,data:W7yVuNKrp6Y=,iv:mM45zqHjSqWsiuosNVzhS5e2rhy4uOmsO4vOzyF9b5c=,tag:xb1oX3ibjVMbwK1syHXe8Q==,type:str]
    SECRET_MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:fG+IobO+4hQ=,iv:RpsJoR3WKjRJpJ9CUQN6HlT2n4R7NJjYhJkwk3DJ4c8=,tag:tgVi/4xGK72xpFXnZXSu8w==,type:str]
    SECRET_SENDGRID_APIKEY_SMTP_RELAY: ENC[AES256_GCM,data:hveMCII5x9Q=,iv:xAODfFk+9l5wu7A4oWS5QDE7kfNsV7BGtYh5L1SDmgs=,tag:zfdxzXsV4VSs2Pp15W7ZMQ==,type:str]
    SECRET_SENDGRID_USER_SMTP_RELAY: ENC[AES256_GCM,data:cAFkhzyGUyM=,iv:AIbuTvp1UtjrGqFxrgB7L8hm6Y9ahGWOGPTn0UoO0C8=,tag:nZWgfgH50epdrPhjZUPzRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p8hda0uw768yg608j8spnwx0fwu5ze88kpchufmgw4v87u2c84dsjns37d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuR1FIVlFGS2o1OVNibVls
            U1ByVzRHdEFiN05HVWVrbGZVdnU4WmYyTjFZClVGYnNKS2UyeFpCaGlHZG1rZTRZ
            U0ZvdWtYVmk4MktEUU1pN2Z0L3V6NXcKLS0tIGlmOFp4QUVFZkl6NHphUDAwendh
            RHk5allvYld1cGJIS0VhelBsVnkzSEUKT3p1+ZD778OPhALj6CQ39QLy4AAvodWZ
            TMsycUlqSAhNt3q5QFlKY87/dejoypRLlogEtXSHdysByqMtKsVL7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-16T20:08:05Z"
    mac: ENC[AES256_GCM,data:DdcKU6qlxR+Z8kzMb253Od0qarSHe6Uh/lT4fAvcqdzgvr2s7Gt0XH71mvjbcNehs2f7Ydatho16CCH31RjG0WacbqP1RQB2R7oZv0tS+6LVYXmbkBpEF31xlJL/+5JIpqxz+xNlupZNhcRLYUs2o5h/VCfBXTCTrhD8AR4jRH4=,iv:HsbVOtudqOp5eWFEe+5Mp2XIG3ZVWv1TRM0PaSuzsq4=,tag:nzUqLs6W0YjQ+nhNlNkfgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
