apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: security
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: network
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:oy62ecDd/ATpyCBBmTbf5Yn3iID98EuonKxibuD9WQZj2OnIDrlAGg==,iv:no1WIIIl8Drz+uCE4G7W/uZhRMXvqccv8q/apMh7QKw=,tag:H0vLYQM1qHYH9pdIThcGag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p8hda0uw768yg608j8spnwx0fwu5ze88kpchufmgw4v87u2c84dsjns37d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdEJuSUhzU2hCZENZWUZF
            dkVTbVRJSGREb1oybnhxS2gvakhSdzREbHdvCmhSOENYMk54WnhaOHRiWDkxNWdy
            dWdLT2pCdFlkSHN2R0FKdncxOHNQbFkKLS0tIHE3K0tDTzZxMVc4c0dtOW5SSWNs
            REpXK3BjemNyZ1RFMkFYNDVsSCs5MFkKB2lnsXc9bgSBlhXWORmIBJMeM/c9zXSe
            NyckvrpyVCDjnOOGwF1zjSGHSW6cTiWCtsU7eIYOHpj6sERCEgWAsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T18:53:20Z"
    mac: ENC[AES256_GCM,data:hMo0c2N/S1aKKLX5hE8ROaRphp3IVN98T3aqDU4No1LiBSxcT2Fuuhd2/L+yg77OA5J89uqtBAFc+PCBRfys6x4LC0CdMCO8rR3B18oxHaxTQNfmCQZ4VHsa/XeoB81zd2rBp9+DFQnyPE51oP6yJoHtlNDo01RhUhRYaEnUqL4=,iv:gLy5OnMvc0lU7jThflyVFNaEMwT/r4ZrcDkHxV5qlBs=,tag:xI3OFYYpCka9PYyXMwFD1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
