apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: network
stringData:
    EXTERNAL_DNS_RFC2136_TSIG_KEYNAME: changeme
    EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG: changeme
    EXTERNAL_DNS_RFC2136_TSIG_SECRET: changeme
