apiVersion: v1
kind: Secret
metadata:
    name: tf-cloud-token
    namespace: flux-system
stringData:
    terraform.tfrc: ENC[AES256_GCM,data:hWqKuV4ZfH8dQFmG3xyzeRRomKlCGo/NBL6lHvOtzA4LfaimVZZUEAViQ0O5HquYvQ5T1eE6sSfOtedDENYFL1FxIBsv5QFVinQ/Dz8gy6Z9gB3sbE4aFSVG,iv:qK2XQTXqmsD/7sH+PwIhZNWmGlky4ZTqLn58Wn9+W50=,tag:HOE5IK3rHRQ6mSl6mtUNXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p8hda0uw768yg608j8spnwx0fwu5ze88kpchufmgw4v87u2c84dsjns37d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVXlWS3p2WmU0ZkdIYnpv
            b252UEFmbitaUHAwdkQwVTI2N3RNeEw0RGdnClVDa1NQTDg4MHNNZG5GWlQrZ21i
            Uy9nMGdZMURHbGNKQ2Jkc0YzSDdCM1EKLS0tICtpYnE4djlUZXdKNXFkckZhVWlW
            emYzWUl0N3Nvak4rblB1WCtMbU9KZzQK4TFAAuzaQIoBYjjWrbLlsa5e3PUhY85C
            bb71qMvrxCI4hfySensgcDQ5hQRjfgvkWJjUXUcT9hoYTypx0qU1pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-27T20:21:33Z"
    mac: ENC[AES256_GCM,data:PMxFzvl7XsIsrz3SNNHvQXefe/roNQVAsug07YFC/WCC3B8KYHpmW0/zQrT7bd7+tOk1/UgoWmcVqX9C3cHiEecraEkJcYYyuUWu9YRa89LDOMfdUl0NmKDGojDNb72SVOD6L1p8yOlxy8WwrfBErFmFCaUu6WSB/OAhomTiBmk=,iv:0QSvQ519w4VHjUOWT9L0mg4dfoJRHUbzvCmvALJqD7o=,tag:rs6S/5cEzUmFBoSU31Es6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
